create database orcamento;
use orcamento;

CREATE TABLE ORCAMENTO (
    ID INTEGER,
    DESCRICAO VARCHAR(500) NOT NULL,
    MES INTEGER NOT NULL,
    ANO INTEGER NOT NULL,
    VALOR_TOTAL_INFORMADO FLOAT NOT NULL,
	CONSTRAINT PK_ORCAMENTO PRIMARY KEY (ID)
);

CREATE TABLE ITEM_ORCAMENTO (
    ID INTEGER auto_increment,
    ORIGEM         		  VARCHAR(200) NOT NULL,
    CODIGO         		  VARCHAR(200) NOT NULL,
    DESCRICAO      		  VARCHAR(500) NOT NULL,
    UNIDADE        		  VARCHAR(200) NOT NULL,
    VALOR_UNITARIO 		  FLOAT NOT NULL,
    QUANTIDADE     		  FLOAT NOT NULL,
    VALOR_TOTAL_INFORMADO FLOAT NOT NULL,
    ID_ORCAMENTO          INTEGER NOT NULL,
	CONSTRAINT PK_ITEM_ORCAMENTO PRIMARY KEY (ID),
    CONSTRAINT FK_ITEM_ORCAMENTO FOREIGN KEY (ID_ORCAMENTO) REFERENCES ORCAMENTO(ID)
);